'use client'
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, Coffee, Leaf, Menu, Minus, Plus, ShoppingBag, Sparkles, Thermometer, Timer, X } from "lucide-react";

type Product={id:number;name:string;origin:string;notes:string;roast:string;brew:string;price:number};
const fallback:Product[]=[
 {id:1,name:"Ethiopia Aricha",origin:"Yirgacheffe, Ethiopia",notes:"Blueberry · Jasmine · Bergamot",roast:"Light",brew:"Pour over",price:22},
 {id:2,name:"Guatemala El Injerto",origin:"Huehuetenango, Guatemala",notes:"Cacao · Red apple · Brown sugar",roast:"Medium",brew:"French press",price:21},
 {id:3,name:"Kenya Gichathaini",origin:"Nyeri, Kenya",notes:"Blackcurrant · Grapefruit · Honey",roast:"Light",brew:"Pour over",price:24},
 {id:4,name:"Costa Rica La Pastora",origin:"Tarrazú, Costa Rica",notes:"Orange · Caramel · Almond",roast:"Medium",brew:"Espresso",price:20},
 {id:5,name:"Rwanda Kinini",origin:"Rulindo, Rwanda",notes:"Apricot · Tea · Wildflower",roast:"Light",brew:"Aeropress",price:23},
 {id:6,name:"Ember House Blend",origin:"East Africa · Central America",notes:"Dark chocolate · Cherry · Toffee",roast:"Medium dark",brew:"Espresso",price:19}];
const nav=[["Shop","#shop"],["Subscriptions","#subscriptions"],["Brew Guides","#guides"],["Events","#events"],["Our Story","#story"]];

export default function Home(){
 const [open,setOpen]=useState(false),[cartOpen,setCartOpen]=useState(false),[sending,setSending]=useState(false),[sent,setSent]=useState(false);
 const [cart,setCart]=useState<Product[]>([]),[products,setProducts]=useState<Product[]>(fallback),[filter,setFilter]=useState("All coffees"),[email,setEmail]=useState(""),[error,setError]=useState("");
 useEffect(()=>{fetch('/api/products').then(r=>r.ok?r.json():Promise.reject()).then(setProducts).catch(()=>null)},[]);
 const shown=useMemo(()=>filter==="All coffees"?products:products.filter(p=>p.roast===filter||p.brew===filter),[filter,products]);
 const add=(p:Product)=>{setCart(c=>[...c,p]);setCartOpen(true)};
 async function submit(e:FormEvent){e.preventDefault();setSending(true);setError("");try{const r=await fetch(`${process.env.NEXT_PUBLIC_CONSTRUCTOR_API}/v1/forms/${process.env.NEXT_PUBLIC_PROJECT_ID}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,interest:"Ember Journal newsletter"})});if(!r.ok)throw Error();setSent(true)}catch{setError("We could not send your signup. Please try again.")}finally{setSending(false)}}
 return <main className="overflow-hidden">
 <nav className="sticky top-0 z-40 border-b bg-cream/95 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#top" className="font-serif text-2xl font-semibold">Ember <span className="text-ember">&</span> Craft</a><div className="hidden gap-8 text-sm lg:flex">{nav.map(([l,h])=><a key={l} href={h} className="hover:text-ember">{l}</a>)}</div><div className="flex"><button aria-label="Open cart" onClick={()=>setCartOpen(true)} className="relative p-3"><ShoppingBag size={20}/>{cart.length>0&&<span className="absolute right-0 top-0 grid h-5 w-5 place-items-center rounded-full bg-ember text-[10px] text-white">{cart.length}</span>}</button><button aria-label="Toggle menu" onClick={()=>setOpen(!open)} className="p-3 lg:hidden">{open?<X/>:<Menu/>}</button></div></div><div className={`absolute left-0 right-0 top-20 border-b bg-cream px-5 py-6 transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] lg:hidden ${open?'pointer-events-auto translate-y-0 opacity-100':'pointer-events-none -translate-y-4 opacity-0'}`}>{nav.map(([l,h],i)=><a key={l} href={h} onClick={()=>setOpen(false)} style={{transitionDelay:open?`${i*60}ms`:'0ms'}} className="block border-b py-3 font-serif text-2xl transition-all">{l}</a>)}</div></nav>

 <section id="top" className="grid min-h-[calc(100vh-5rem)] lg:grid-cols-2"><div className="grain flex items-center px-6 py-20 md:px-12 lg:px-[8vw]"><div className="max-w-xl"><p className="mb-5 text-xs font-bold uppercase tracking-[.24em] text-ember">Small batch · Direct trade · Roasted weekly</p><h1 className="text-6xl leading-[.92] font-semibold md:text-7xl">Roasted fresh,<br/><em className="font-normal">delivered weekly.</em></h1><p className="mt-7 text-lg leading-8 text-earth">Specialty single origin and experimental blends, sourced directly from twelve farms across East Africa and Central America.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#shop" className="flex items-center justify-center gap-2 rounded-lg bg-ember px-6 py-4 font-semibold text-white">Explore our roasts <ArrowRight size={18}/></a><a href="#subscriptions" className="rounded-lg border border-ink px-6 py-4 text-center font-semibold">Join our tasting club</a></div></div></div><div className="relative min-h-[520px] overflow-hidden bg-[radial-gradient(circle_at_42%_38%,#D4A574_0,#8A4828_28%,#2A2520_68%)]"><div className="absolute inset-0 bg-[linear-gradient(120deg,transparent_45%,rgba(255,217,157,.22)_48%,transparent_57%)]"/><div className="drum absolute left-[14%] top-[12%] aspect-square h-[72%] rounded-full border-[22px] border-[#4b372b] bg-[repeating-radial-gradient(ellipse_at_center,#4f2417_0_9px,#2c1711_10px_16px)] shadow-[inset_0_0_70px_#000,0_20px_70px_#1b100b]"/>{["left-[18%] top-[22%]","right-[16%] top-[34%]","left-[24%] bottom-[20%]"].map((p,i)=><div key={p} className={`bean absolute ${p} h-12 w-7 rounded-[60%_40%] bg-[#6d331d] shadow-xl`} style={{animationDelay:`${i*.7}s`}}/>)}<p className="absolute bottom-8 left-8 max-w-xs font-serif text-2xl text-white">Golden light. First crack. The week begins here.</p></div></section>

 <section id="shop" className="bg-paper px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid items-end gap-6 border-b pb-8 lg:grid-cols-2"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-ember">Fresh from the roaster</p><h2 className="text-5xl">Our single origins</h2></div><p className="text-earth lg:justify-self-end">Distinct coffees with a clear sense of place. Every bag includes its harvest story, ideal recipe, and roast date.</p></div><div className="grid gap-px bg-border md:grid-cols-3">{products.slice(0,3).map((p,i)=><article key={p.id} className="bg-paper py-10 md:px-6"><div className={`mb-8 grid aspect-[4/3] place-items-center rounded-lg text-white ${i===0?'bg-[#9A5737]':i===1?'bg-[#6B5B47]':'bg-forest'}`}><Coffee size={72} strokeWidth={1}/></div><p className="text-xs uppercase tracking-widest text-earth">{p.origin}</p><h3 className="mt-2 text-3xl">{p.name}</h3><p className="mt-2 text-sm text-earth">{p.notes}</p><div className="mt-6 flex justify-between"><b>${p.price} / 12 oz</b><button onClick={()=>add(p)} aria-label={`Add ${p.name} to cart`} className="rounded-full bg-ink p-3 text-white"><Plus size={18}/></button></div></article>)}</div></div></section>

 <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-ember">The coffee shelf</p><h2 className="mt-3 text-5xl">Find your daily ritual</h2></div><div className="flex flex-wrap gap-2">{["All coffees","Light","Medium","Espresso","Pour over"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full border px-4 py-2 text-sm ${filter===x?'bg-ink text-white':''}`}>{x}</button>)}</div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{shown.map((p,i)=><article key={p.id} className="overflow-hidden rounded-xl border bg-paper"><div className={`grid h-44 place-items-center ${['bg-[#B16A43]','bg-forest','bg-tan'][i%3]}`}><Coffee className="text-white" size={60} strokeWidth={1}/></div><div className="p-6"><div className="flex justify-between"><h3 className="text-2xl">{p.name}</h3><b>${p.price}</b></div><p className="text-sm text-earth">{p.origin}</p><p className="mt-4 text-sm">{p.notes}</p><div className="mt-5 flex justify-between border-t pt-4 text-xs uppercase tracking-wider"><span>{p.roast} roast</span><button onClick={()=>add(p)} className="flex items-center gap-1 font-bold text-ember">Add to bag <Plus size={14}/></button></div></div></article>)}</div></div></section>

 <section id="story" className="bg-ink px-5 py-28 text-cream"><div className="mx-auto max-w-4xl text-center"><Leaf className="mx-auto text-tan"/><p className="mt-6 text-xs font-bold uppercase tracking-[.24em] text-tan">From seed to cup</p><h2 className="mt-5 text-5xl md:text-6xl">Coffee tastes better when every hand in its story is valued.</h2><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-white/70">We build long term relationships with producers across twelve coffee growing countries and roast each coffee to make its origin unmistakable.</p></div></section>
 <section className="grid bg-forest px-5 py-12 text-white sm:grid-cols-2 lg:grid-cols-4">{[["847","Coffee lovers"],["18","Awards won"],["12,000+","Pounds roasted monthly"],["Zero","Waste packaging"]].map(([n,l])=><div key={l} className="border-white/20 p-6 text-center lg:border-r"><strong className="font-serif text-5xl">{n}</strong><p className="mt-2 text-sm text-white/75">{l}</p></div>)}</section>

 <section id="guides" className="bg-paper px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-ember">Brew with confidence</p><h2 className="mt-3 text-5xl">A better cup is in the details.</h2></div><div className="grid gap-px bg-border sm:grid-cols-2">{[[Timer,"Pour over mastery","3:15 minutes · Medium fine · 200°F"],[Thermometer,"French press fundamentals","4 minutes · Coarse · 205°F"],[Coffee,"Espresso setup","28 seconds · Fine · 198°F"],[Sparkles,"Cold brew patience","18 hours · Coarse · Room temperature"]].map(([Icon,title,meta])=>{const I=Icon as typeof Timer;return <article key={title as string} className="bg-paper p-7"><I className="text-ember"/><h3 className="mt-6 text-2xl">{title as string}</h3><p className="mt-2 text-sm text-earth">{meta as string}</p><a href="#newsletter" className="mt-5 inline-flex items-center gap-1 text-sm font-bold">Get the recipe <ArrowRight size={14}/></a></article>})}</div></div></section>

 <section id="events" className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-ember">Gather around the table</p><h2 className="mt-3 text-5xl">Upcoming tastings</h2><div className="mt-10 divide-y border-y">{[["Public cupping: East Africa","Monthly · Saturday morning","Roastery tasting room","$25 · 12 spots"],["Pour over masterclass","Monthly · Thursday evening","Roastery brew bar","$45 · 8 spots"],["Virtual origin tasting","Quarterly · Sunday afternoon","Live online session","$35 · 20 spots"]].map(([a,b,c,d])=><article key={a} className="grid items-center gap-4 py-7 md:grid-cols-[1.4fr_1fr_1fr_auto]"><div><h3 className="text-2xl">{a}</h3><p className="text-sm text-earth">{b}</p></div><p className="text-sm">{c}</p><b className="text-sm">{d}</b><a href="#newsletter" className="rounded-lg border border-ink px-5 py-3 text-center text-sm font-semibold">Request a spot</a></article>)}</div></div></section>

 <section id="subscriptions" className="bg-[#EFE4D8] px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-ember">A season of exceptional coffee</p><h2 className="mt-3 text-5xl">Choose your tasting pace</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{[["Single Bag","$18","One fresh single origin monthly","Tasting notes and brew guide","Free domestic shipping"],["Explorer Subscription","$45","Three rotating origins monthly","Experimental blend access","Priority event registration"],["Connoisseur Club","$89","Five coffees including rare lots","Private virtual cuppings","Early limited release access"]].map((t,i)=><article key={t[0]} className={`relative rounded-xl border p-7 ${i===1?'border-ember bg-ember text-white':'bg-paper'}`}>{i===1&&<span className="absolute right-5 top-5 rounded-full bg-white px-3 py-1 text-xs font-bold text-ember">Most popular</span>}<h3 className="text-3xl">{t[0]}</h3><p className="mt-5 font-serif text-5xl">{t[1]}<small className="font-sans text-sm"> / month</small></p><ul className="mt-7 space-y-3 text-sm">{t.slice(2).map(x=><li key={x} className="flex gap-2"><Check size={16}/>{x}</li>)}</ul><a href="#newsletter" className={`mt-8 block rounded-lg px-5 py-3 text-center font-semibold ${i===1?'bg-white text-ember':'bg-ink text-white'}`}>Join the club</a></article>)}</div></div></section>

 <section className="bg-paper px-5 py-24"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-3">{[["SC","After years of grocery store coffee, these single origins completely changed my morning ritual. The tasting notes actually match what I experience.","Sarah Chen","Product Manager · San Francisco"],["MW","The monthly subscription introduced me to coffees I would never have discovered alone. The curated notes feel like having a personal roaster.","Marcus Williams","Freelance Designer · Austin"],["JP","We served their espresso blend at our wedding and guests could not stop asking about it. Quality and service that genuinely impress.","Jessica & David Park","Event Planner and Chef · Seattle"]].map(([ini,q,n,r],i)=><figure key={n} className={`rounded-xl p-8 ${i===1?'bg-ink text-white':'bg-cream'}`}><div className="mb-8 grid h-16 w-16 place-items-center rounded-full bg-tan font-serif text-xl text-ink">{ini}</div><blockquote className="font-serif text-2xl leading-8">“{q}”</blockquote><figcaption className="mt-7 text-sm"><b>{n}</b><br/><span className="opacity-60">{r}</span></figcaption></figure>)}</div></section>

 <section id="newsletter" className="bg-ember px-5 py-16 text-white"><div className="mx-auto grid max-w-7xl items-center gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/70">Notes from the roastery</p><h2 className="mt-2 text-4xl">Brew guides, limited lots, good gatherings.</h2></div>{sent?<p className="text-lg font-semibold">✓ Message sent — we will be in touch soon</p>:<form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row"><input aria-label="Email address" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address" className="min-w-0 flex-1 rounded-lg border border-white/40 px-5 py-4 placeholder:text-white/70"/><button disabled={sending} className="rounded-lg bg-ink px-7 py-4 font-semibold">{sending?'Sending…':'Join the journal'}</button>{error&&<p className="text-sm">{error}</p>}</form>}</div></section>
 <footer className="bg-ink px-5 py-16 text-cream"><div className="mx-auto max-w-7xl"><div className="grid gap-10 border-b border-white/15 pb-12 md:grid-cols-4"><div className="md:col-span-2"><p className="font-serif text-3xl">Ember <span className="text-ember">&</span> Craft</p><p className="mt-4 max-w-sm text-sm text-white/60">Specialty coffee roasted with clarity, sourced with care, and shared in good company.</p></div>{[nav.slice(0,3),nav.slice(3)].map((group,i)=><div key={i}><h3 className="font-sans text-xs uppercase tracking-widest text-tan">{i?'Learn':'Explore'}</h3>{group.map(([l,h])=><a key={l} href={h} className="mt-3 block text-sm text-white/70">{l}</a>)}</div>)}</div><p className="pt-7 text-xs text-white/45">© 2026 Ember & Craft. Thoughtfully roasted.</p></div></footer>

 <div className={`fixed inset-0 z-50 transition ${cartOpen?'pointer-events-auto bg-black/40':'pointer-events-none bg-transparent'}`} onClick={()=>setCartOpen(false)}><aside onClick={e=>e.stopPropagation()} className={`absolute right-0 h-full w-full max-w-md bg-cream p-6 transition-transform duration-500 ${cartOpen?'translate-x-0':'translate-x-full'}`}><div className="flex justify-between"><h2 className="text-3xl">Your coffee bag</h2><button aria-label="Close cart" onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length===0?<div className="grid h-2/3 place-items-center text-center text-earth"><p>Your bag is ready for something remarkable.</p></div>:<><div className="mt-8 space-y-4">{cart.map((p,i)=><div key={`${p.id}-${i}`} className="flex justify-between border-b pb-4"><div><p className="font-serif text-xl">{p.name}</p><small>Whole bean · 12 oz</small></div><div className="flex gap-3"><span>${p.price}</span><button aria-label={`Remove ${p.name}`} onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}><Minus size={16}/></button></div></div>)}</div><div className="absolute bottom-6 left-6 right-6"><p className="mb-4 flex justify-between font-bold"><span>Subtotal</span><span>${cart.reduce((n,p)=>n+p.price,0)}</span></p><a href="#newsletter" onClick={()=>setCartOpen(false)} className="block rounded-lg bg-ember p-4 text-center font-semibold text-white">Request checkout details</a></div></>}</aside></div>
 </main>}
